general:
  debug: false
stats:
  configversion: ${project.config.version}
  trackcreativemode: false
  database:
    sql_db_version: ${project.database.version}
    type: "sqlite"
    host: "localhost"
    username: "Beardstats"
    password: "changeme"
    database: "stats"
    table: "stats"
    prefix: "stats"
    port: 3306
